baseURL = 'https://blog.cryptoblog21.xyz/'
languageCode = 'en-us'
title = 'Random Notes'
theme = 'docsy'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[params.katex]
enable = true

[[params.katex.options.delimiters]]
  left = "$$"
  right = "$$"
  display = true
[[params.katex.options.delimiters]]
  left = "\\begin{align}"
  right = "\\end{align}"
  display = true
[[params.katex.options.delimiters]]
  left = "$"
  right = "$"
  display = false

